### ISSUE TITLE
Error when trying to run python3 tvh_main.py in ubuntu

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [rocky4546/tvheadend-locast#1]
```
Traceback (most recent call last):                                              
  File "tvh_main.py", line 11, in <module>                                      
    main.main(script_dir)                                                       
  File "/tvheadend-locast-0.7.3-RC2/lib/tvheadend/main.py", line 65, in main    
    utils.logging_setup(configObj.config_file)                                  
  File "/tvheadend-locast-0.7.3-RC2/lib/tvheadend/utils.py", line 15, in logging
_setup                                                                          
    logging.config.fileConfig(fname=config_file)                                
  File "/usr/lib/python3.8/logging/config.py", line 71, in fileConfig           
    formatters = _create_formatters(cp)                                         
  File "/usr/lib/python3.8/logging/config.py", line 104, in _create_formatters  
    flist = cp["formatters"]["keys"]                                            
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__           
    raise KeyError(key)                                                         
KeyError: 'formatters' 
```

**Comment by rocky4546** [comment]
Thank you for the submission.
You are missing parameters in the config.ini file. To get past the error, add the following to the config.ini that should be located at /tvheadend-locast-0.7.3-RC2/
You can also checkout the config_example.ini located at /tvheadend-locast-0.7.3-RC2/lib/tvheadend/ for more information.

[loggers]
keys = root

[logger_root]
level = DEBUG
handlers = loghandler

[handlers]
keys = loghandler

[formatters]
keys = extend,simple

[handler_loghandler]
class = StreamHandler
formatter = extend
args = (sys.stdout,)

[formatter_extend]
format = %(asctime)s-%(levelname)s: %(message)s

[formatter_simple]
format = %(levelname)s: %(message)s

**Comment by cookie-monster-bit** [comment]
Thank you that worked!
I was looking at the config_example.ini in the root directory.
